from __future__ import annotations

from pathlib import Path

from intelligent_liars import activation_loaders as _loaders
from intelligent_liars.activation_extract import (
    _chunks,
    extract_dataset_activations,
    extract_masked_decoder_activations,
    qwen_decoder_num_layers,
)
from intelligent_liars.activation_hdf5 import (
    _activation_shard_queue_plan_id,
    _activation_shards_have_disjoint_tasks,
    _collect_merged_activation_task,
    _copy_disjoint_activation_hdf5_tasks,
    _copy_disjoint_activation_task,
    _copy_root_attrs,
    _decode_hdf5_scalar,
    _delete_task_outputs,
    _extraction_settings_attrs,
    _jsonable_metadata,
    _jsonable_value,
    _layer_indices_for_task,
    _merge_activation_shard,
    _merge_resume_metadata_attrs,
    _normalize_compression_mode,
    _safe_hdf5_name,
    _task_metadata_attrs,
    _tasks_in_activation_handle,
    _tasks_in_activation_shard,
    _tasks_in_activation_shards,
    _tensor_sequence_to_numpy,
    _verify_activation_shard_queue_plan_ids,
    _verify_dataset_shape_compatible,
    _verify_layer_metadata_compatible,
    _verify_merge_task_attrs_compatible,
    _verify_metadata_compatible,
    _verify_root_attrs_compatible,
    _version_metadata,
    _write_activation_shard,
    default_activation_output_path,
    merge_activation_hdf5_shards,
    write_activation_hdf5,
)
from intelligent_liars.activation_loaders import (
    _apply_task_detection_trim,
    _detected_texts,
    _example,
    _infer_task_from_rollout_path,
    _label_schema_for_rollout,
    _load_claim_examples,
    _load_combined_examples,
    _load_ethics_examples,
    _load_geometry_of_truth_examples,
    _load_insider_trading_examples,
    _load_internal_state_examples,
    _load_repe_examples,
    _load_simpleqa_examples,
    _load_sycophancy_examples,
    _message,
    _normalise_input_message,
    _normalise_output_message,
    _normalise_rollout_input_message,
    _read_csv_dicts,
    _repe_prompts,
    _resolve_data_dir,
    _resolve_data_file,
    _rollout_output_messages_for_index,
    _rollout_output_strs,
    _sample_simpleqa_distractor,
    _simpleqa_answer_type,
    _split_final_detected_message,
    _split_statement_tail,
    _sycophancy_example,
    normalise_deception_label,
)
from intelligent_liars.activation_masks import (
    DetectionMaskBuilder,
    QwenProcessorTokenizer,
    _absolute_detection_spans,
    _append_content,
    _build_answer_detection_mask_detail,
    _build_message_detection_mask_detail,
    _build_qwen_inputs,
    _content_blocks,
    _decoded_detection_text_matches,
    _find_content_flexible,
    _find_expected_text_span,
    _is_quote_boundary_extra,
    _normalise_for_compare,
    _qwen_content,
    _qwen_messages,
    _same_token_ids,
    _shift_mask_for_next_token_logits,
    _tensorish_to_list,
    _token_candidates,
    _usable_position_mask,
    build_answer_detection_mask,
    merge_consecutive_messages_with_spans,
    render_activation_example,
    verify_decoded_masks,
)
from intelligent_liars.activation_types import (
    DECEPTIVE,
    HONEST,
    INSIDER_REPORT_LABELS,
    SANDBAGGING_LABELS,
    SKIP,
    STRING_DECEPTION_LABELS,
    ActivationDataset,
    ActivationExample,
    ActivationExtractionSettings,
    ActivationExtractionSummary,
    ActivationMergeSummary,
    DetectionMask,
    DetectionSegment,
    Label,
    LabelSchema,
    LocalDetectionSpan,
    MergedMessageSpan,
    ProcessorBatch,
    RenderedDetectionExample,
    _content_text,
    parse_layer_spec,
)
from intelligent_liars.activation_backends import ActivationBackend
from intelligent_liars.models import ModelBundle
from intelligent_liars.rollouts import MODEL_SLUG


STEM_TASKS_PART_1 = _loaders.STEM_TASKS_PART_1
STEM_TASKS_PART_2 = _loaders.STEM_TASKS_PART_2
GOT_MIXED_CSVS = _loaders.GOT_MIXED_CSVS
GOT_BEST_CSVS = _loaders.GOT_BEST_CSVS
COMBINED_COMPONENT_TASKS = _loaders.COMBINED_COMPONENT_TASKS


def _sync_loader_constants() -> None:
    _loaders.STEM_TASKS_PART_1 = STEM_TASKS_PART_1
    _loaders.STEM_TASKS_PART_2 = STEM_TASKS_PART_2
    _loaders.GOT_MIXED_CSVS = GOT_MIXED_CSVS
    _loaders.GOT_BEST_CSVS = GOT_BEST_CSVS
    _loaders.COMBINED_COMPONENT_TASKS = COMBINED_COMPONENT_TASKS


def load_rollout_activation_examples(
    path: Path, *, task: str | None = None
) -> list[ActivationExample]:
    return _loaders.load_rollout_activation_examples(path, task=task)


def load_named_activation_examples(
    task: str,
    *,
    project_root: Path,
    generated_model: str = MODEL_SLUG,
) -> list[ActivationExample]:
    _sync_loader_constants()
    return _loaders.load_named_activation_examples(
        task,
        project_root=project_root,
        generated_model=generated_model,
    )


def extract_rollout_activations(
    *,
    bundle: ModelBundle,
    rollout_path: Path,
    output_path: Path,
    settings: ActivationExtractionSettings,
    task: str | None = None,
    overwrite: bool = False,
    backend: ActivationBackend | None = None,
) -> ActivationExtractionSummary:
    if backend is None and bundle.model is None:
        raise ValueError("Activation extraction requires a loaded model.")

    dataset = ActivationDataset.from_rollout(rollout_path, task=task)
    return extract_dataset_activations(
        bundle=bundle,
        dataset=dataset,
        output_path=output_path,
        settings=settings,
        overwrite=overwrite,
        backend=backend,
    )


__all__ = [
    "DECEPTIVE",
    "HONEST",
    "INSIDER_REPORT_LABELS",
    "SANDBAGGING_LABELS",
    "SKIP",
    "STRING_DECEPTION_LABELS",
    "ActivationDataset",
    "ActivationExample",
    "ActivationExtractionSettings",
    "ActivationExtractionSummary",
    "ActivationMergeSummary",
    "COMBINED_COMPONENT_TASKS",
    "DetectionMask",
    "DetectionMaskBuilder",
    "DetectionSegment",
    "GOT_BEST_CSVS",
    "GOT_MIXED_CSVS",
    "Label",
    "LabelSchema",
    "LocalDetectionSpan",
    "MergedMessageSpan",
    "ProcessorBatch",
    "QwenProcessorTokenizer",
    "RenderedDetectionExample",
    "STEM_TASKS_PART_1",
    "STEM_TASKS_PART_2",
    "_absolute_detection_spans",
    "_activation_shard_queue_plan_id",
    "_activation_shards_have_disjoint_tasks",
    "_apply_task_detection_trim",
    "_append_content",
    "_build_answer_detection_mask_detail",
    "_build_message_detection_mask_detail",
    "_build_qwen_inputs",
    "_chunks",
    "_collect_merged_activation_task",
    "_content_blocks",
    "_content_text",
    "_copy_disjoint_activation_hdf5_tasks",
    "_copy_disjoint_activation_task",
    "_copy_root_attrs",
    "_decoded_detection_text_matches",
    "_decode_hdf5_scalar",
    "_delete_task_outputs",
    "_detected_texts",
    "_example",
    "_extraction_settings_attrs",
    "_find_content_flexible",
    "_find_expected_text_span",
    "_infer_task_from_rollout_path",
    "_is_quote_boundary_extra",
    "_jsonable_metadata",
    "_jsonable_value",
    "_label_schema_for_rollout",
    "_layer_indices_for_task",
    "_load_claim_examples",
    "_load_combined_examples",
    "_load_ethics_examples",
    "_load_geometry_of_truth_examples",
    "_load_insider_trading_examples",
    "_load_internal_state_examples",
    "_load_repe_examples",
    "_load_simpleqa_examples",
    "_load_sycophancy_examples",
    "_merge_activation_shard",
    "_merge_resume_metadata_attrs",
    "_message",
    "_normalise_for_compare",
    "_normalise_input_message",
    "_normalise_output_message",
    "_normalise_rollout_input_message",
    "_normalize_compression_mode",
    "_qwen_content",
    "_qwen_messages",
    "_read_csv_dicts",
    "_repe_prompts",
    "_resolve_data_dir",
    "_resolve_data_file",
    "_rollout_output_messages_for_index",
    "_rollout_output_strs",
    "_safe_hdf5_name",
    "_same_token_ids",
    "_sample_simpleqa_distractor",
    "_shift_mask_for_next_token_logits",
    "_simpleqa_answer_type",
    "_split_final_detected_message",
    "_split_statement_tail",
    "_sycophancy_example",
    "_sync_loader_constants",
    "_task_metadata_attrs",
    "_tasks_in_activation_handle",
    "_tasks_in_activation_shard",
    "_tasks_in_activation_shards",
    "_tensor_sequence_to_numpy",
    "_tensorish_to_list",
    "_token_candidates",
    "_usable_position_mask",
    "_verify_activation_shard_queue_plan_ids",
    "_verify_dataset_shape_compatible",
    "_verify_layer_metadata_compatible",
    "_verify_merge_task_attrs_compatible",
    "_verify_metadata_compatible",
    "_verify_root_attrs_compatible",
    "_version_metadata",
    "_write_activation_shard",
    "build_answer_detection_mask",
    "default_activation_output_path",
    "extract_dataset_activations",
    "extract_masked_decoder_activations",
    "extract_rollout_activations",
    "load_named_activation_examples",
    "load_rollout_activation_examples",
    "merge_activation_hdf5_shards",
    "merge_consecutive_messages_with_spans",
    "normalise_deception_label",
    "parse_layer_spec",
    "qwen_decoder_num_layers",
    "render_activation_example",
    "verify_decoded_masks",
    "write_activation_hdf5",
]
