from __future__ import annotations

# ruff: noqa: F401

import logging

from intelligent_liars.clients.openrouter_client import (
    OpenRouterAPIError,
    fetch_openrouter_key_metadata,
    fetch_openrouter_model_endpoint_metadata,
    get_model_client,
)
from intelligent_liars.insider_grader import (
    _doubling_down_email_from_transcript,
    _doubling_down_message_from_transcript,
    _extract_trade_amount,
    _first_detectable_assistant_message,
    _grade_insider_trading_rollout_output,
    _insider_record_is_graded,
    _last_assistant_message,
    _render_double_down_prompt,
    _report_message_from_transcript,
    classify_doubling_down_message,
    classify_insider_report_message,
    classify_trade_message,
    extract_email,
    extract_reasoning,
    grade_insider_trading_record,
    grade_insider_trading_transcripts,
    validate_one_action,
)
from intelligent_liars.judge_client import (
    _call_openrouter_judge,
    _extract_openrouter_text,
    _get_openrouter_session,
    _handle_error,
    _json_judge_structured_instruction,
    _parse_required_judgement,
    _provider_routing_for_structured_outputs,
    _run_tagged_judge,
    _safe_text_context,
    _should_retry_judge_error,
    call_judge,
    convert_response_to_json,
    convert_response_to_object,
    grade_single_dialogue_for_deception,
    json_judge_response_format,
    parse_judgement,
    run_json_judge,
)
from intelligent_liars.judge_config import (
    DEFAULT_INSIDER_GRADING_FLUSH_EVERY,
    DEFAULT_JUDGE_CONFIG,
    DEFAULT_OPENROUTER_JUDGE_MODEL,
    DEFAULT_ROLLOUT_GRADING_FLUSH_EVERY,
    DEFAULT_ROLLOUT_GRADING_MAX_WORKERS,
    ROLEPLAYING_SYSTEM_POSTFIX,
    GradingSummary,
    JudgeConfig,
    JudgePreflight,
    JudgeProvider,
    Judgement,
    Message,
    PromptGetter,
    _endpoint_provider_keys,
    _filter_endpoints_for_provider_routing,
    _normalised_provider_values,
    preflight_judge_config,
)
from intelligent_liars.roleplaying_grader import (
    _first_message_content,
    _grade_roleplaying_output,
    _parse_structured_roleplaying_grade,
    _roleplaying_structured_instruction,
    _run_structured_roleplaying_judge,
    _scenario_from_messages,
    _validate_roleplaying_judgement,
    build_roleplaying_grading_prompt,
    grade_roleplaying_dialogue,
    roleplaying_response_format,
)
from intelligent_liars.rollout_grading import (
    _doubling_down_email_from_rollout_record,
    _ensure_output_grading_lists,
    _grade_insider_trading_rollout_data,
    _grade_roleplaying_rollout_data,
    _grade_sandbagging_rollout_data,
    _is_deceptive_judgement,
    _is_scorable_judgement,
    _is_ungraded,
    _padded_list,
    _record_source_index,
    _rollout_output_message,
    _selected_indices,
    _selected_rollout_record_indices,
    _set_deception_percentage,
    _set_insider_rollout_metadata,
    grade_rollout_file,
    infer_rollout_task,
)
from intelligent_liars.rollouts import parse_task_name, write_json_atomic
from intelligent_liars.sandbagging_grader import (
    extract_tag_content,
    label_sandbagging_response,
)


logger = logging.getLogger(__name__)


__all__ = [
    "DEFAULT_INSIDER_GRADING_FLUSH_EVERY",
    "DEFAULT_JUDGE_CONFIG",
    "DEFAULT_OPENROUTER_JUDGE_MODEL",
    "DEFAULT_ROLLOUT_GRADING_FLUSH_EVERY",
    "DEFAULT_ROLLOUT_GRADING_MAX_WORKERS",
    "ROLEPLAYING_SYSTEM_POSTFIX",
    "GradingSummary",
    "JudgeConfig",
    "JudgePreflight",
    "JudgeProvider",
    "Judgement",
    "Message",
    "OpenRouterAPIError",
    "PromptGetter",
    "build_roleplaying_grading_prompt",
    "call_judge",
    "classify_doubling_down_message",
    "classify_insider_report_message",
    "classify_trade_message",
    "convert_response_to_json",
    "convert_response_to_object",
    "extract_email",
    "extract_reasoning",
    "extract_tag_content",
    "fetch_openrouter_key_metadata",
    "fetch_openrouter_model_endpoint_metadata",
    "get_model_client",
    "grade_insider_trading_record",
    "grade_insider_trading_transcripts",
    "grade_roleplaying_dialogue",
    "grade_rollout_file",
    "grade_single_dialogue_for_deception",
    "infer_rollout_task",
    "json_judge_response_format",
    "label_sandbagging_response",
    "parse_judgement",
    "parse_task_name",
    "preflight_judge_config",
    "roleplaying_response_format",
    "run_json_judge",
    "validate_one_action",
    "write_json_atomic",
]
